### ISSUE TITLE
extra botany crash on server

### ISSUE THREAD

**Issue by spyguy26** [ExtraMeteorP/Extra-Botany#1]
while attemting to use the latest version of extra botany on my server it crashes when it gets to loading extra botany

here's the crash log
https://gist.github.com/spyguy26/069cde12e2a352905f0b15c7f6db04f9

I'm using, forge 1.12.2 - 14.23.4.2705

Botania r1.10-354.jar

and ExtraBotany-r1.1-33.jar

**Comment by ExtraMeteorP** [comment]
Thanks for feedback, it will be fixed in next update.
Before that, you can use quick fix version instead in server.
Download here: http://www.mediafire.com/file/82d8dfsytaq1q72/ExtraBotany-r1.1-33-quickfix.jar/file
