### ISSUE TITLE
Goggles of Revealing variants for headgears

### ISSUE THREAD

**Issue by angelnc1989** [ExtraMeteorP/Extra-Botany#10]
Botania always had the possibility to add Goggles of Revealing from Thaumcraft to their helmets. It would be cool to see that feature in Extra Botany too.

**Comment by ExtraMeteorP** [comment]
I'm quite busy these days, so I will release the next update a few days later.

**Comment by angelnc1989** [comment]
No rush =D

**Comment by ExtraMeteorP** [comment]
Done
