### ISSUE TITLE
Core of god (rainbow) and ring of curse

### ISSUE THREAD

**Issue by HM0ra** [ExtraMeteorP/Extra-Botany#101]
Hi friends!
I want to ask you about your addon for Botania (Extrabotany). How to craft the core of god (rainbow) and upgrade ring of curse?
Thank you in advance<3

**Comment by HM0ra** [comment]
> Hi friends!
> I want to ask you about your addon for Botania (Extrabotany). How to craft the core of god (rainbow) and upgrade ring of curse?
> Thank you in advance<3

**Comment by ExtraMeteorP** [comment]
rainbow is dropped from herrscher with 2% chance. not supported on spongeforge server yet.
and ring of curse can not be upgraded.
