### ISSUE TITLE
The movement of Enchanted Orchid is asymmetric

### ISSUE THREAD

**Issue by HoshinoTented** [ExtraMeteorP/Extra-Botany#103]
[This code](https://github.com/ExtraMeteorP/Extra-Botany/blob/34cee8ebffd0151257261eb7911b5e5684f6b31f/src/main/java/com/meteor/extrabotany/common/block/subtile/functional/SubTileEnchantedOrchid.java#L77):

```java
int r = ConfigHandler.EO_RANGE;
		
if(consumed >= shouldCost){
	for(int x = -r; x < r; x++)
		for(int z = -r; z < r; z++){
			if(getWorld().getBlockState(getPos().add(x, -1, z)).getBlock() == Blocks.GRASS && hasIngot){
				if(!getWorld().isRemote)
						getWorld().setBlockState(getPos().add(x, -1, z), ModBlocks.enchantedSoil.getDefaultState());
				hasIngot = false;
				consumed = 0;
				break;
			}	
		}
}
``` 

Because of the `<` operator, it will transform 8 * 1 * 8 grass blocks to Enchanted Soil: 4 blocks in the negative direction of the x-axis, and 3 in the positive direction. The z-axis too.

Is it a bug?

**Comment by ExtraMeteorP** [comment]
yes, thanks for reporting
