### ISSUE TITLE
Mana Liquefaction Device - Not working / not using correctly?

### ISSUE THREAD

**Issue by maxell45146** [ExtraMeteorP/Extra-Botany#11]
![2018-09-03_03 21 03](https://user-images.githubusercontent.com/2869265/44972849-9ea58380-af28-11e8-9d09-9f8d0d820757.png)

From what I read in the guide this block is post to convert mana in a pool into a different liquid that can be stored in a tank. I've tried a couple different setups but nothing seems to work. Attached is what I currently have setup, redstone signal is on, tank is sitting on it, mana pool has mana but no go. 

Just wondering if there is a issue with this block at the moment or if I'm missing something really simple.

**Comment by ExtraMeteorP** [comment]
The redstone signal stop the pump from working, you’d better use a spark or a spreader.

**Comment by maxell45146** [comment]
![2018-09-03_05 50 47](https://user-images.githubusercontent.com/2869265/44980325-88ee8900-af3d-11e8-9018-b79de3b2b9c0.png)

Spark isnt working either. Something I did notice though when looking in JEI is that the mod doesnt have a liquid as one of its items. Based off the guide when a redstone signal is applied it should be converting the mana to the liquid and outputting to the tank.

**Comment by ExtraMeteorP** [comment]
Then try mana spreader.
I think this spark isn’t linked with a mana pool.

**Comment by maxell45146** [comment]
![2018-09-03_13 53 32](https://user-images.githubusercontent.com/2869265/44998090-cf190c00-af80-11e8-8875-3b58f26c129a.png)
Already tried mana spreader, same result. Picture is of the same setup from a different angle, even right clicked on the spark to show that it has a connection to the one sitting on the pool.

**Comment by ExtraMeteorP** [comment]
This will be fixed in next update. I forgot that Primal Mana in Thermal Expansion is also using the name "mana" when it is registered, then it cause conflict.

**Comment by ExtraMeteorP** [comment]
Done
