### ISSUE TITLE
额外植物学的成就导致服务器崩溃

### ISSUE THREAD

**Issue by 824312808** [ExtraMeteorP/Extra-Botany#111]
在服务器做完成就之后成就给予物品会给予一大堆，然后导致服务器崩溃，重载之后每次更新成就都会导致这个问题，同时有时候自己会突然触发这个bug，有解决办法吗，没有找到相关的配置文件修改

**Comment by ExtraMeteorP** [comment]
暂无

**Comment by 824312808** [comment]
那成就配置文件哪里能改？就改成完成成就不给奖励
