### ISSUE TITLE
盖亚三战斗bug反馈

### ISSUE THREAD

**Issue by 1ChenFeng** [ExtraMeteorP/Extra-Botany#112]
1：召唤的盖亚并无显形，但可见碰撞箱
2：攻击到盖亚后会造成游戏内黑屏现象
求解决方案！

**Comment by ExtraMeteorP** [comment]
请附上mod列表及对应版本

**Comment by 1ChenFeng** [comment]
Minecraft版本：1.12.2
额外植物学版本：ExtraBotany-r1.1-55
启动器：PCL2
资源包：Minecraft-Mod-Language-Modpack（汉化万用包），PCL离线自定义皮肤资源包
Mods list（整合包：提尔空岛）:
minecraft - Minecraft - 1.12.2
mcp - Minecraft Coder Pack - 9.42
FML - Forge Mod Loader - 8.0.99.99
forge - Minecraft Forge - 14.23.5.2847
jecharacters - Just Enough Characters - 1.12.0-3.3.0
smoothfontcore - Smooth Font Core - mc1.12.2-1.16
openmodscore - OpenModsLib Core - 0.12.2
smoothfont - Smooth Font - mc1.12.2-1.16.2
codechickenlib - CodeChicken Lib - 3.2.2.354
item_search - Item Search - 1.0.0
chameleon - Chameleon - 1.12-4.1.3
storagedrawers - Storage Drawers - 1.12-5.3.5
ctm - CTM - MC1.12.2-0.3.3.22
chisel - Chisel - MC1.12.2-0.2.1.35
torcherino - Torcherino - 7.6
endercore - EnderCore - 1.12.2-0.5.72
baubles - Baubles - 1.5.2
crafttweaker - CraftTweaker2 - 4.1.20
endertweaker - EnderTweaker - 1.1.7
mtlib - MTLib - 3.0.6
modtweaker - Mod Tweaker - 4.0.17
jei - Just Enough Items - 4.14.3.238
redstoneflux - Redstone Flux - 2.1.0
cofhcore - CoFH Core - 4.6.1
brandonscore - Brandon's Core - 2.4.9
cofhworld - CoFH World - 1.3.0
thermalfoundation - Thermal Foundation - 2.6.3
draconicevolution - Draconic Evolution - 2.3.18
thermalexpansion - Thermal Expansion - 5.5.4
thaumcraft - Thaumcraft - 6.1.BETA26
enderio - Ender IO - 5.1.52
enderiointegrationtic - Ender IO Integration with Tinkers' Construct - 5.1.52
ccm - Craftable Creative Modifier - 1.0
mantle - Mantle - 1.12-1.3.3.55
tconstruct - Tinkers' Construct - 1.12.2-2.12.0.157
ic2 - IndustrialCraft 2 - 2.8.187-ex112
openmods - OpenModsLib - 0.12.2
openblocks - OpenBlocks - 1.8.1
guideapi - Guide-API - 1.12-2.1.7-62
mousetweaks - Mouse Tweaks - 2.10
projecte - ProjectE - 1.12.2-PE1.4.1
p455w0rdslib - p455w0rd's Library - 2.0.22
appliedenergistics2 - Applied Energistics 2 - rv6-stable-7
wct - Wireless Crafting Terminal 2 - 3.10.82
ironchest - Iron Chest - 1.12.2-7.0.54.838
enderstorage - EnderStorage - 2.4.5.135
enderiobase - Ender IO Base - 5.1.52
enderioconduits - Ender IO Conduits - 5.1.52
enderioconduitsappliedenergistics - Ender IO Applied Energistics Conduits - 5.1.52
enderioconduitsopencomputers - Ender IO Open Computers Conduits - 5.1.52
refinedstorage - Refined Storage - 1.6.12
enderioconduitsrefinedstorage - Ender IO Refined Storage Conduits - 5.1.52
forestry - Forestry - 5.8.2.394
enderiointegrationforestry - Ender IO Integration with Forestry - 5.1.52
enderiointegrationticlate - Ender IO Integration with Tinkers' Construct - 5.1.52
ftblib - FTB Library - 5.4.4.5
enderiomachines - Ender IO Machines - 5.1.52
enderiopowertools - Ender IO Powertools - 5.1.52
instantunify - InstantUnify - 1.1.2
thaumictinkerer - Thaumic Tinkerer - 1.12.2-5.0-353c71c
bonsaitrees - Bonsai Trees - 1.1.2
mcmultipart - MCMultiPart - 2.5.3
mekanism - Mekanism - 1.12.2-9.8.1.383
sonarcore - SonarCore - 5.0.19
calculator - Calculator - 5.0.11
waila - Waila - 1.8.26
botania - Botania - r1.10-361
extrabotany - ExtraBotany - 55
advanced_solar_panels - Advanced Solar Panels - 4.3.0
bdlib - BD Lib - 1.14.3.12
ae2stuff - AE2 Stuff - 0.7.0.4
aroma1997core - Aroma1997Core - 2.0.0.2
aromabackup - AromaBackup - 2.1.1.4
aromabackuprecovery - AromaBackuprecovery - 2.1.1.4
avaritia - Avaritia - 3.2.0
avaritiarecipemaker - Avaritia Recipe Maker - 1.0.0
avaritiatweaks - Avaritia Tweaks - 1.12.2-1.1
botanianeedsit - Botania Needs These Things! - 1.12.2-3.0-release
cyclopscore - Cyclops Core - 1.6.0
colossalchests - Colossal Chests - 1.6.11
compactmachines3 - Compact Machines 3 - 3.0.18
controlling - Controlling - 3.0.6
ctgui - CT-GUI - 1.0.0
crafttweakerjei - CraftTweaker JEI Support - 2.0.3
cucumber - Cucumber Library - 1.1.3
enderioendergy - Ender IO endergy - 5.1.52
extracells - Extra Cells 2 - 2.6.1
extrautils2 - Extra Utilities 2 - 1.0
zerocore - Zero CORE - 1.12-0.1.2.3
bigreactors - Extreme Reactors - 1.12.2-0.4.5.50
fastleafdecay - Fast Leaf Decay - v14
fluxnetworks - Flux Networks - 3.0.19
forgelin - Shadowfacts' Forgelin - 1.8.2
forgemultipartcbe - Forge Multipart CBE - 2.6.0.79
microblockcbe - Forge Microblocks - 2.6.0.79
minecraftmultipartcbe - Minecraft Multipart Plugin - 2.6.0.79
ftbutilities - FTB Utilities - 5.4.0.124
itemfilters - Item Filters - 1.0.3.12
ftbquests - FTB Quests - 1.8.0.237
gardenofglass - Garden of Glass - sqrt(-1)
immersiveengineering - Immersive Engineering - 0.12-88
immersivecables - Immersive Cables - 1.3.2
immersivepetroleum - Immersive Petroleum - 1.1.9
immersivetech - Immersive Tech - 1.3.10
inventorytweaks - Inventory Tweaks - 1.63+release.109.220f184
jeibees - JEI Bees - 0.9.0.5
jeresources - Just Enough Resources - 0.8.5.27
journeymap - JourneyMap - 1.12.2-5.5.3
mcjtylib_ng - McJtyLib - 3.0.7
mtrm - MineTweakerRecipeMaker - 1.2.2.30
modularmachinery - Modular Machinery - 1.11.1
mysticalagriculture - Mystical Agriculture - 1.7.5
mysticalagradditions - Mystical Agradditions - 1.3.2
mystagradcompat - Mystical Agradditions Compat - 1.2
recipehandler - NoMoreRecipeConflict - 0.12
oreexcavation - OreExcavation - 1.4.137
projectex - Project EX - 1.2.0.39
refined_avaritia - Refined Avaritia - 2.4
rftools - RFTools - 7.59
rftoolsdim - RFTools Dimensions - 5.63
skyresources - Sky Resources 2 - 2.3.8
sc - Sky Compression - 1.2.2.1
spawncommands - Spawn Commands - 2.7.2alpha
taiga - Tinkers Alloying Addon - 1.12.2-1.3.3
thaumicenergistics - Thaumic Energistics - 2.0.0
thaumicequivalence - Thaumic Equivalence - 1.12.2-1.0.5
tcinventoryscan - Thaumcrafft Inventory Scanning - 2.0.10
tinkersaddons - Tinkers' Addons - 1.0.7
tp - Tiny Progressions - 3.2.32
treegrowingsimulator - Tree Growing Simulator 2016 - 0.0.4
valkyrielib - Valkyrie Lib - 1.12.2-2.0.18.1
universalmodifiers - Universal Modifiers - 1.12.2-1.0.16.1
voidislandcontrol - Void Island Control - 1.5.3
wailaharvestability - Waila Harvestability - 1.1.12
waterpower - WaterPower - @MODVERSION@
mekanismgenerators - Mekanism: Generators - 1.12.2-9.8.1.383
astralsorcery - Astral Sorcery - 1.10.20
aroma1997sdimension - Aroma1997's Dimensional World - 2.0.0.2
tinker_io - Tinker I/O - rw2.7.1
flyringbaublemod - AngelRing 2 Bauble - 0.3.1_1.12-d4e654e
harvestcraft - Pam's HarvestCraft - 1.12.2zb
jehc - Just Enough HarvestCraft - 1.12.2
environmentaltech - Environmental Tech - 1.12.2-2.0.18.2
thaumicjei - ThaumicJEI - 1.2.1
bloodmagic - Blood Magic: Alchemical Wizardry - 1.12.2-2.3.3-101
BBOutlineReloaded-1.0.13-1.12.2-forge

**Comment by ExtraMeteorP** [comment]
请先更新至r58以上，如还有此问题再反馈
