### ISSUE TITLE
1.12.2 Sponge端 解锁成就时 StackOverflow

### ISSUE THREAD

**Issue by CitrusSin** [ExtraMeteorP/Extra-Botany#122]
如题  
[crash-report](https://pastebin.com/ehNdPEMw)都快上千行了。。。。。把循环节标出来了方便阅读（（  
服务器的有关信息，哪位玩家的操作导致的bug啥的crash-report里面应该写得挺明白  
因为我也不是很懂到底是哪个成就 我就把当事人描述贴上来  

当事人描述(walksQAQ)：  
> 草  
> 我啥都没干  
> 真·啥都没干  
> 只是在一直在飞行状态  
> 然后在查exbot的东西  

我：

> 此前你不是说叠了啥BUFF？

walksQAQ: 

> 对啊
> 但那玩意没成就
> 遗物·静籁永恒是没有成就的
> 你只要确定那玩意是成就相关那必然和这个无关
> 我只能怀疑是剩下这堆遗物有个重复扫描了n遍的

顺便提一句，Sponge会通过mixin动态修改字节码来实现更改某些原版class的行为，而且crash-report里面坐实了这一点
所以我不求修复有多么快，只求你们看到了如果有空最好修一下（（
谢谢！

**Comment by walksQAQ** [comment]
那个 附加个问题 待着待着会莫名其妙爆一地精卫之羽 extrabotany版本 r1.1-60

**Comment by ExtraMeteorP** [comment]
鹅 忘记回复了 抱歉。
这个问题 只能说我不太了解Sponge，不是很好解决啊。
目前忙着写1.16.5的版本，1.12.2的修复版可能得到国庆了。
这个问题我大概只能先用折中点的方法，例如配置文件内取消成就相关设定来解决。

**Comment by Micrafast** [comment]
> 鹅 忘记回复了 抱歉。
> 这个问题 只能说我不太了解Sponge，不是很好解决啊。
> 目前忙着写1.16.5的版本，1.12.2的修复版可能得到国庆了。
> 这个问题我大概只能先用折中点的方法，例如配置文件内取消成就相关设定来解决。

谢谢！这个bug不急着修，有临时方案也完全够了

**Comment by walksQAQ** [comment]
啊对了 当时是从r1.1-58升级至r1.1-60后开始出的问题

**Comment by Kantets** [comment]
Any updates?
