### ISSUE TITLE
Game crashing when opening inventory with extra-Botany Items [1.16.5]

### ISSUE THREAD

**Issue by YeroHD** [ExtraMeteorP/Extra-Botany#123]
As written in the Title the game crashes, when i open (creative tabs and survival) inventory if there are items from ExtraBotany

I attached the crash log

LG

[latest.log](https://github.com/ExtraMeteorP/Extra-Botany/files/7116022/latest.log)

**Comment by ExtraMeteorP** [comment]
https://www.mediafire.com/file/rm828oo91o6hufg/ExtraBotany-r1.2-63-alpha-1.jar/file 
try this one

**Comment by YeroHD** [comment]
Yes, thank you very much, now it is working without any problems^^
