### ISSUE TITLE
1.16.5 通过jei和创造模式物品栏获取两个贤者魔力指环后存档崩溃无法进入

### ISSUE THREAD

**Issue by walksQAQ** [ExtraMeteorP/Extra-Botany#125]
额外植物学版本为 r1.2-64-alpha-fix 一指环为空指环经jei获取后由火花部分充能 崩档前mana值为8960338 另一指环为创造模式物品栏获取为满存储魔力 nbtexplorer查看崩溃存档中指环nbt数据，其显示mana值为-2147483638 多次加载存档由pcl2反馈的错误原因均一致为exbot
最后一次的crashreport:
[crash-2021-09-11_19.22.11-client.txt](https://github.com/ExtraMeteorP/Extra-Botany/files/7147688/crash-2021-09-11_19.22.11-client.txt)
最后一次的运行log:
[latest.log](https://github.com/ExtraMeteorP/Extra-Botany/files/7147691/latest.log)
[debug.log](https://github.com/ExtraMeteorP/Extra-Botany/files/7147692/debug.log)
NBTExplorer截图:
![image](https://user-images.githubusercontent.com/62731307/132946716-5d35c9fe-def3-4565-a9b3-774d20602963.png)

**Comment by ExtraMeteorP** [comment]
fixed in r66
