### ISSUE TITLE
1.16.5 Power Frame didn't drop the object that was in it

### ISSUE THREAD

**Issue by Pqvel1l** [ExtraMeteorP/Extra-Botany#127]
I put a TerraSteelAIOT item with enchantments from the Botania AIOT mod and couldn't pick it up from the frame. And after breaking it , he disappeared altogether

**Comment by ExtraMeteorP** [comment]
shift+rightclick to get it out. i will check and fix the latter one.

**Comment by ExtraMeteorP** [comment]
fixed in r66
