### ISSUE TITLE
Cant use tool while charging mana.

### ISSUE THREAD

**Issue by xRoBoTx** [ExtraMeteorP/Extra-Botany#128]
While wearing Pleiades Combat Maid Armor or any other armor that charge tools you cant mine with tools due to NBT changing.
![Bug](https://user-images.githubusercontent.com/28825932/133172245-a42faea2-b219-4020-bb76-986c0e3c9e53.gif)

**Comment by ExtraMeteorP** [comment]
fixed in r66
