### ISSUE TITLE
[Bug?] Potion Lens cant be crafted

### ISSUE THREAD

**Issue by JuicyCosmos** [ExtraMeteorP/Extra-Botany#130]
1.16.5的mod版本
36.2.2的Forge版本
1.2-67的mod版本
药水滤镜好像无法与药水合成，没有用
原版的、植物魔法的都不行，是不是药水滤镜还没有完全functional呀？还是出bug了

**Comment by ExtraMeteorP** [comment]
和鸡尾酒合成

**Comment by JuicyCosmos** [comment]
学会了，谢谢！
