### ISSUE TITLE
What is this? 

### ISSUE THREAD

**Issue by ZiSXD** [ExtraMeteorP/Extra-Botany#144]
![stardustlotus](https://user-images.githubusercontent.com/109520745/179498550-7ec2c0a0-c87e-490c-9204-3c7d7c361d6a.png)

I saw this picture in the "Images" section, but in the game itself there is no such lotus. Is this some kind of leaky new version of the mod or what?

**Comment by ExtraMeteorP** [comment]
1.12.2 has, removed in 1.16
