### ISSUE TITLE
Flux Manafield not accepting FE

### ISSUE THREAD

**Issue by Thedrummonger** [ExtraMeteorP/Extra-Botany#15]
I can not seem to get any energy cables to connect to the mana flux field meaning it is unable to receive energy to work. I have tried with Ender IO conduits, Thermal Ducts, Fulx networks and immersive cables. I will attack a picture as well.
![2018-09-16_09 50 55](https://user-images.githubusercontent.com/16329331/45597737-24e4af80-b996-11e8-821e-e6c8f274831d.png)

I have verified that the flux manafeild is enabled in the config. I'll attach that as well.
https://pastebin.com/ARfXTsvH

Forge 14.23.4.2757
ExtraBotany r1.1-42-fixed
Botania r1.10.356

**Comment by ExtraMeteorP** [comment]
![2018-09-21_21 35 59](https://user-images.githubusercontent.com/10953378/45884449-84075180-bde6-11e8-8158-e20086cc8dfd.png)
Add Compat in r43.
