### ISSUE TITLE
[1.12.2] Missing Name for Shadowium

### ISSUE THREAD

**Issue by NickelHub** [ExtraMeteorP/Extra-Botany#16]
As the title says.
![2018-09-21_19 39 03](https://user-images.githubusercontent.com/26455012/45897081-6b8f3b00-bdd6-11e8-9e48-0b291b11fa72.png)

**Comment by ExtraMeteorP** [comment]
Thanks for feedback.
It seems that I make a typo mistake in lang.

**Comment by ExtraMeteorP** [comment]
Done
