### ISSUE TITLE
Dependancy Baubles needs to be lower case

### ISSUE THREAD

**Issue by Rikshy** [ExtraMeteorP/Extra-Botany#18]
https://github.com/ExtraMeteorP/Extra-Botany/blob/5f5bcdbcfe79af2e2b00986bf74db25f38edbaf1/src/main/java/com/meteor/extrabotany/ExtraBotany.java#L35

pretty much title: modids are lowercase :)

**Comment by ExtraMeteorP** [comment]
Got it

**Comment by ExtraMeteorP** [comment]
Done
