### ISSUE TITLE
[1.1-33] Server crash on start-up

### ISSUE THREAD

**Issue by ruyanve** [ExtraMeteorP/Extra-Botany#2]
Hey,

tried the latest version on Forge 2756 and got this:
https://hastebin.com/uximixafoy.rb

Cheers

**Comment by ExtraMeteorP** [comment]
Thanks for feedback, it will be fixed in next update.
Before that, you can use quick fix version instead in server.
Download here: http://www.mediafire.com/file/82d8dfsytaq1q72/ExtraBotany-r1.1-33-quickfix.jar/file

**Comment by ruyanve** [comment]
Sorry mate, was busy today...
Didn't test 1.1-33 but 1.1-34 starts just fine.
Cheers, awesome support! <3
