### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Thinggyblop** [ExtraMeteorP/Extra-Botany#22]
Crashes on start up and not sure what is causing it.

[crash-2018-10-20_00.13.19-client.txt](https://github.com/ExtraMeteorP/Extra-Botany/files/2496318/crash-2018-10-20_00.13.19-client.txt)

**Comment by ExZha1337** [comment]
Me too.

https://paste.dimdev.org/afaxakahos.mccrash

**Comment by CrankySupertoon01** [comment]
Same
[crash-2018-10-19_19.34.40-client.txt](https://github.com/ExtraMeteorP/Extra-Botany/files/2497628/crash-2018-10-19_19.34.40-client.txt)

**Comment by ExtraMeteorP** [comment]
Sorry for late reply. That's my fault due to my carelessness. 
As Curse need time to verify the file, I've uploaded one to mediafire.
http://www.mediafire.com/file/o3vyv2z11wzo5eo/ExtraBotany-r1.1-45-fixed.jar/file

**Comment by ExZha1337** [comment]
Thank you for your quick work. :)
