### ISSUE TITLE
Server Side Crash: TileEntitySpecialRenderer at com.meteor.extrabotany.common.item.ItemHalloweenCandy.onSpawn(ItemHalloweenCandy.java:102)

### ISSUE THREAD

**Issue by hendersont2** [ExtraMeteorP/Extra-Botany#23]
[crash-2018-10-28_15.12.55-server.txt](https://github.com/ExtraMeteorP/Extra-Botany/files/2523107/crash-2018-10-28_15.12.55-server.txt)

There is the crash log. No Extra Botany items should have been present int the world, but it appears that some time after a player enters the world this crash causes the entire server to crash.

**Comment by hendersont2** [comment]
What is more, it may be world corrupting since I don't seem to be able to start the server without crashing, even after Extra Botany was removed.

**Comment by ExtraMeteorP** [comment]
try setting enable.candybag to false in the config and see whether it still cause crash.
the crash seems strange，i will test it soon.

**Comment by minakitty** [comment]
It hit me too just now.  I'll disable the candybag

**Comment by minakitty** [comment]
Wondering, is the candy bag a time limited thing for Halloween?

**Comment by ExtraMeteorP** [comment]
Nope，but there is a higher chance to see it in halloween. A bug fix update is gonna to be released this weekend

**Comment by minakitty** [comment]
Does 1.1-47 fix the bug, or is it still being worked on?

**Comment by ExtraMeteorP** [comment]
fixed
