### ISSUE TITLE
奥利哈刚匠魂材料属性介绍空白

### ISSUE THREAD

**Issue by magcicada** [ExtraMeteorP/Extra-Botany#27]
如图，是我眼花了还是咋了？？
![qq 20181204144008](https://user-images.githubusercontent.com/45464670/49428014-dd74ff00-f7df-11e8-8ca7-393501db86a6.png)

**Comment by ExtraMeteorP** [comment]
因为没想好非常coool的效果 所以暂时留白
实际效果也是非常朴素呢
如果你有脑洞的话可以留言

**Comment by magcicada** [comment]
@ExtraMeteorP 那你倒是介绍下材料的效果特性到底是啥啊，我都不知道这个属性具体会引起什么效果，咋给你写介绍啊

**Comment by ExtraMeteorP** [comment]
我的意思是现在没效果

**Comment by magcicada** [comment]
卒……那我还是提个建议吧，就看你能实现不。
肉体：植物的魔力，凝结为不毁的防御（加几点伤害吸收效果）
精神：魔法的滋润让我感觉更加强大（加力量效果）
灵魂：魔法的攻击让敌人溃不成军（对怪物施加凋零效果）
简单点吧，太复杂了也不好，差不多这样子就行了，这也是我的个人建议，采不采纳取决与你，挨打流年                                                          😂
