### ISSUE TITLE
CraftTweaker Integration not working properly

### ISSUE THREAD

**Issue by MasterEnderman** [ExtraMeteorP/Extra-Botany#28]
Forge: 14.23.5.2795
Extra Botany: 1.1-48-fixed
Botania: 1.10-358
JEI: 4.14.0.231
CraftTweaker: 4.1.13

I tried to modify the recipes in the Livingrock Pedestal.  After reloading the pack no errors occured and my newly added recipes are working fine, but don't show up in JEI.

**Comment by ExtraMeteorP** [comment]
i have no idea at present. need further investigation

**Comment by pupnewfster** [comment]
I am also having this issue. It sounds like the recipes are being registered after JEI tries to grab the recipes. I poked around a bit through IntelliJ and it seems you are doing all the CraftTweaker stuff in loadComplete. I would recommend either running the recipe stuff when CraftTweaker normally does or if you want it to be delayed, run it in postInit. That way it will have been run before JEI looks at any items.

**Comment by ExtraMeteorP** [comment]
ohhh, it works! thank you for your help!
