### ISSUE TITLE
Garden of Glass and Stonesia balance and compat issue

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [ExtraMeteorP/Extra-Botany#3]
The stonesia is a bit OP in the garden of glass setting even though it is an end game mana generating flower. Is it intentional that it produces more mana than the orechid consumes to produce the ores it feeds the stonesia with? Not sure if this was intentional or not.

I'm sure however that the Stonesia does not consume ores from immersive engineering in my test. Unsure if it is the same with other modded ores. It would be great if the stonesia is consistent.

**Comment by ExtraMeteorP** [comment]
Thanks for feedback.
I will try to balance stonesia. It's intentional to make it produce more mana than orechid consumes so that it can be a way to generate mana.
I'm a bit lazy so I didn't use oredict when coding :X  
The compact will take effect in next update.

**Comment by TheGuyFromTheInternet** [comment]
I see. Thank you :)
