### ISSUE TITLE
Mana Buffer and Quantum Mana Buffer not working

### ISSUE THREAD

**Issue by leftyde** [ExtraMeteorP/Extra-Botany#31]
Hello,

I tried to use your mod in my Enigmatica 2 Expert Mode world and I found out, that I can't fill those Mana Buffers. I used just a normal Mana Spreader, Elven Mana Spreader and Gaia Mana Spreader, but it's not filling up.

If I read correctly, I just need a Mana Pool on top of it but does it require something else or is it just an Bug?

I'm using Botania: r1.10-358 and ExtraBotany: R1.1-49(48)

**Comment by ExtraMeteorP** [comment]
Need further investigation.
Currently it can pump mana from a mana pool next to it. You can just place a pool below.

**Comment by ExtraMeteorP** [comment]
will fix in next update
