### ISSUE TITLE
Violating the Botania License

### ISSUE THREAD

**Issue by yrsegal** [ExtraMeteorP/Extra-Botany#34]
As the [Botania License](https://botaniamod.net/license.php) states, all botania dependants must do the following:

> Copyleft Clause
> Your project must be open source (have its source visible and allow for redistribution and modification) and include a clause similar to this one in its license.

Since you seem to have taken this mod closed source as of 2c4ffd800dca4e825aeb33a4efbacae49aa188e5, you are violating that clause.

**Comment by ExtraMeteorP** [comment]
since I haven’t updated the mod, the code of r50 is here https://github.com/ExtraMeteorP/Extra-Botany/tree/4fd84b0f7b4f533cd31da023fc1f6bbed44af730

**Comment by yrsegal** [comment]
My point is that, for the future, it is against the license to continue the mod without having the code open for anyone.
