### ISSUE TITLE
Extreme lag spike when Gaia MK3 launches those unique pixies

### ISSUE THREAD

**Issue by border999** [ExtraMeteorP/Extra-Botany#38]
I've got a stupidly powerful laptop, and I'm still hitting pretty much zero when it comes to FPS when I try to fight Gaia MK3 because of those oppenents he sends out. Is it possible that your mod has a problem with optifine or something?

**Comment by ExtraMeteorP** [comment]
dont you build the arena on a water field？gaia will destroy liquid block

**Comment by border999** [comment]
yes I did, however i did disable it's destructive abilities through the config.

**Comment by border999** [comment]
also this started happening today and I'd like your weigh-in.

**Comment by border999** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/3770

**Comment by border999** [comment]
https://paste.dimdev.org/urayifedam.mccrash and here's the crashlog is you just don't care to check that link.

**Comment by border999** [comment]
also. I know it's the pixies and the mines because there are moments during my 1 FPS fight that things go back to normal, and that's when all of those things have disappeared.

**Comment by ExtraMeteorP** [comment]
that’s weird, you’re the first who has problem with those opponents...
And for the crash report, I haven’t updated tinker construct compat yet, it seems that tic has something changed.

**Comment by ExtraMeteorP** [comment]
My tic compat is based on tinker construct-1.12.2-2.10.1.87. (Nearly 5 months ago) My fault, I will update the compat soon.

**Comment by border999** [comment]
still really odd though, because the crash only started today. it was all working yesterday.

**Comment by ExtraMeteorP** [comment]
really weird, I have updated to TConstruct-1.12.2-2.12.0.115 and conarm-1.12.2-1.2.3, but there is no such problem :X

**Comment by border999** [comment]
in the same boat here man, like I said "started happening yesterday"  I've tried removing the configs for the mods. still crashes. No ideas.

**Comment by border999** [comment]
updated, crash still occurs. Recommendation, implementation of some sort of check to see it tinkers has already added stats for a material before adding it's own.

**Comment by ExtraMeteorP** [comment]
maybe you can try disabling construct armory support in extrabotany.cfg

**Comment by border999** [comment]
doesn't work. Because it doesn't get to that config before the crash. My evidence? I removed that config and it has yet to regenerate before a crash yet
Also I have tried turning it off and it still doesn't help

**Comment by border999** [comment]
can confirm now, using global update function to force change the config option fixed the issue. Also taking a  look at the area under my  battle with the guardian proved you correct. It was trying to erase all the water. Why it was only doing this at certain times during the fight I do not know but filling in the ocean underneath the arena fixed the extreme lag of the fight.  quick question can I only hurt your MK3 with botania tools? and even then only for 8 damage at a time?

**Comment by border999** [comment]
I recommend just looking into this stuff, especially that config bug.

**Comment by ExtraMeteorP** [comment]
Botania, vanilla and extrabotany tools. Enchantments and potions are suggested. 
I will check that bug.
