### ISSUE TITLE
nature orb is consumed when activating Gaia MK3 fight

### ISSUE THREAD

**Issue by border999** [ExtraMeteorP/Extra-Botany#39]
nough said

**Comment by ExtraMeteorP** [comment]
will be fixed in next update

**Comment by border999** [comment]
ETA on next update?

**Comment by ExtraMeteorP** [comment]
tomorrow, if everything goes well, or I have to put off for a week due to my study

**Comment by border999** [comment]
do you happen to have a discord or a jenkins for this mod?

**Comment by ExtraMeteorP** [comment]
yep， https://discord.gg/FFEzvtr
