### ISSUE TITLE
mastermanaring bug

### ISSUE THREAD

**Issue by Xiazihong** [ExtraMeteorP/Extra-Botany#4]
植物魔法版本: Botania+r1.10-354.jar
额外植物学版本: ExtraBotany-r1.1-36

BUG过程:
1.当你穿戴植物魔法的泰拉套 
2.然后戴上 mastermanaring(大师魔力之戒) 游戏崩溃 之后一上线就崩溃
(和自然温息宝珠也会)

崩溃日志:
https://paste.ubuntu.com/p/sBTXQ8Hspt/

**Comment by ExtraMeteorP** [comment]
谢谢反馈 下次更新会修复

**Comment by ExtraMeteorP** [comment]
已更新
