### ISSUE TITLE
Request for source code of 1.7.10

### ISSUE THREAD

**Issue by tyker1** [ExtraMeteorP/Extra-Botany#41]
i came across to see the extra-botany mods for 1.7.10 is been abandoned, i wanted to take over that project for 1.7.10, can u pls send me (or open a reposity for) the source code for 1.7.10?

在MCBBS上看到dalao的mod，因为个人比较喜欢1.7.10版本所以一直在玩1.7.10的，然后发现dalao的1.7.10版弃坑了，github上也没找到源码，想要接手1.7.10版的开发，dalao是否能把1.7.10的源码给我呢？

**Comment by ExtraMeteorP** [comment]
https://github.com/ExtraMeteorP/ExtraBotany/settings
很高兴有人想接手，如果可以的话我希望能尽量向1122的内容靠齐
之所以停更1710的原因如下：
内容写的太杂了..弄了很多然并卵的东西，等到r21开始删减时候我进高中了，没时间维护了
前段时间稍微有空了，但此时国外主流已经是1122了，虽然1710玩家很多，但继续开发1710显然不是一个很好的决定，因为时间并不够我同时更新两个版本。我现在的时间也就够我维护一下1122。
如果你愿意继续维护的话希望你能帮我把那些然并卵的东西删掉

**Comment by tyker1** [comment]
上面那个链接是404哦

我会尝试修改那些然并卵的东西，并且努力项1122版本靠拢的

**Comment by ExtraMeteorP** [comment]
https://github.com/ExtraMeteorP/ExtraBotany

**Comment by tyker1** [comment]
想着手开始修改。。发现给的这个代码似乎跟发布的最后一个版本（r21）有些对不上。。r21里面应该已经移除了d20和一些遗物以及加入了诸神套。。但是github上这个repository里版本号实际是r18.。(或者r20），这些改动都还没有被实装的状态。。？

**Comment by ExtraMeteorP** [comment]
最终代码得等我今天放学打包传一下

**Comment by ExtraMeteorP** [comment]
[src.zip](https://github.com/ExtraMeteorP/Extra-Botany/files/2977801/src.zip)
最终的已经找不到了 这份相对完整一点
