### ISSUE TITLE
Bugs in new update ExtraBotany-r1.1-52

### ISSUE THREAD

**Issue by TheDirectorX** [ExtraMeteorP/Extra-Botany#42]
**Bottled Flame**
* Torches drop out of inventory when you are flying at night.
* Torches can be put on the Air block (Empty block)
* Torches endlessly trying to put in a vertical tunnel

In my opinion, it is better to do so that the Torches check where they can be put only on illumination 7 and lower. And it is better that the Torches are not put in liquids and other similar blocks.
![2019-03-28_03 42 39](https://user-images.githubusercontent.com/43481085/55120701-e2581880-5118-11e9-8dac-b7bdee7ba192.png)

**Bottled Pixie**
+ They spawn in blocks, and if they do not see the enemies, they simply stand and suffocate in the blocks

It is necessary to increase the height of the summon in order to summon at the level of the player’s torso or head
![2019-03-28_03 48 34](https://user-images.githubusercontent.com/43481085/55120739-03206e00-5119-11e9-8c4f-77917a4d15d9.png)

**Bottled Star**
+ Causes severe FPS drop

It’s probably better to make the stars fall to a certain point where the player is looking (as in Terraria). So there will be less effects (lags) and it will be less unbalanced.
![2019-03-28_03 52 24](https://user-images.githubusercontent.com/43481085/55120817-4b3f9080-5119-11e9-96c0-6a463b44e580.png)

**Comment by ExtraMeteorP** [comment]
improved
