### ISSUE TITLE
Text overflowing in the Lexica Botania

### ISSUE THREAD

**Issue by Dimentive** [ExtraMeteorP/Extra-Botany#46]
In the Lexica Botania, there’s a visual bug where the text goes outside the book GUI on the “From The New World (1/1).” I don’t know if it happens on any other pages, but I haven’t seen it happen anywhere in the Lexica Botania other than this page from ExtraBotany.

![ExtraBotany bug (cropped)](https://user-images.githubusercontent.com/34230933/55839516-70280080-5b28-11e9-8c84-db6eb434cab1.png)

OptiFine is installed. I don’t know if OptiFine is causing this, but the mod has caused text-related issues before, such as in the Tinkers’ Construct book, so it might be the cause.

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2825 (latest)
* **Botania:** r1.10-360 (latest)
* **ExtraBotany:** r1.1-53 (latest)
* **OptiFine:** HD U E4 pre3 (latest preview build)

**Comment by ExtraMeteorP** [comment]
my bad. The overflowing text is telling the way to get spirit fuel. At least the way to unlock knowledge can be seen clearly
