### ISSUE TITLE
ALL FOR ONE ring & Elven King rings not working

### ISSUE THREAD

**Issue by SomeRandomPetey** [ExtraMeteorP/Extra-Botany#48]
I have a bauble case with a few baubles in it, but neither the ALL FOR ONE ring or the Elven King ring are activating them. is there something else I have to do?
![image](https://user-images.githubusercontent.com/42192920/56366941-36a76300-61c2-11e9-85ed-e24c20ae769a.png)

**Comment by ExtraMeteorP** [comment]
sorry for letting you down, but it now just support those baubles which won’t check whether you actually equip it. 
In botania, aura ring, blood pendant, cloud pendant, magnet ring, ice pendant, lava pendant, water ring, swap ring, tiny planet.
In extrabotany, exclude crown and core of god.

**Comment by SomeRandomPetey** [comment]
ah. I guess I'm still limited in terms of bauble space.
