### ISSUE TITLE
Config option to disable Flux Manafield and shields

### ISSUE THREAD

**Issue by angelnc1989** [ExtraMeteorP/Extra-Botany#5]
I love that you have config options to disable all the flowers. It would be nice to have the option to disable the Flux Manafield and the 3 non-relic shields.  
Especially the Flux Manafield. I think it's completly against the spirit of Botania.

**Comment by ExtraMeteorP** [comment]
:D I will consider it.

**Comment by angelnc1989** [comment]
The Flux Manafield is still craftable after setting the config option to false.

**Comment by ExtraMeteorP** [comment]
But it will not work after being disabled.

**Comment by angelnc1989** [comment]
Okay. Didn't test that. Then I will remove it with CraftTweaker.

**Comment by ExtraMeteorP** [comment]
Nope :P I'm just a bit lazy
