### ISSUE TITLE
GaiaIII item dupe glitch

### ISSUE THREAD

**Issue by bigenergy** [ExtraMeteorP/Extra-Botany#50]
Gaia level 3 dupe
https://www.youtube.com/watch?v=KJnzD_RpQEk&feature=youtu.be

**Comment by bigenergy** [comment]
@ExtraMeteorP please see video - https://www.youtube.com/watch?v=KJnzD_RpQEk&feature=youtu.be

**Comment by ExtraMeteorP** [comment]
i see, I will try to fix it
