### ISSUE TITLE
Shadowium blade world corruption

### ISSUE THREAD

**Issue by adstheorganic** [ExtraMeteorP/Extra-Botany#51]
Preface: I have vaniallafix installed

When using the shadowium blade and wearing botania or extra botany armour, then the game crashes to the point where you cannot re-enter your world (vanilla fix blocks his telling you of the crash on each re-entry attempt but I believe its because it fully corrupts the world)  to the point where you need to restore from a backup. The error is 

java.lang.NoSuchMethodError: vazkii.botania.api.mana.IManaDiscountArmor.getDiscount(

You can get a similar error from botania itself so there is an issue on that end but those only cause minor errors and not corruption so here's the full Pastebin https://paste.dimdev.org/ihadamivib.mccrash

**Comment by ExtraMeteorP** [comment]
weird. I asked some people to do that but none of them got a crash. need further investigation

**Comment by adstheorganic** [comment]
Huh, since you were not able to reproduce it, I'll give a bit more detail, The only other thing I think could be related is that I was testing this against the Gaia guardian 3. (In hindsight I don't think i tested against any other mobs) 
The crash happened when I hit the boss with the Shaowium katana. 
And just to add, although I'm fairly sure these do not affect it, I know it crashed with both Terrasteel and maid armour. 
And on the off chance, it is another mod causing issues this was tested on the pack: The Culmination version 2.2.0. (I would suggest taking ToMeTinkers out because it causes the load time to be quadrupled to over 20 minutes)

**Comment by ExtraMeteorP** [comment]
the crash is caused because some mod is using outdated botania api
