### ISSUE TITLE
Bugs and suggestions

### ISSUE THREAD

**Issue by TheDirectorX** [ExtraMeteorP/Extra-Botany#58]
- [x]  **(Maybe Bug)** Gaia III begins to quickly destroy the liquid blocks, because of this there are lags.
_By the way, I did not notice when Gaia from Botania also began to destroy blocks of water._
![2019-06-13_19 11 20](https://user-images.githubusercontent.com/43481085/59439712-2ea91f80-8e0f-11e9-8c4b-1c955fc1f0ff.png)
![2019-06-12_18 17 36](https://user-images.githubusercontent.com/43481085/59370004-0fe95100-8d5b-11e9-9ce2-28bdbc1feb36.png)
![2019-06-12_18 17 04](https://user-images.githubusercontent.com/43481085/59370005-1081e780-8d5b-11e9-98e1-7c7c43400dac.png)

- [x]  **(Suggestion)** Add a slight delay before starting a battle with Gaia III. Something like that, as implemented in Botania with Gaia I and Gaia II.
![2019-06-12_21 48 06](https://user-images.githubusercontent.com/43481085/59445697-851b5b80-8e19-11e9-9cff-0471811b036d.png)

- [x] **(Improvements)** Add spaces (or brackets) for bag descriptions Eins, Zwei, Drei, etc. in the end.
![image](https://user-images.githubusercontent.com/43481085/59446095-4afe8980-8e1a-11e9-9107-6271a664514f.png)

**Comment by ExtraMeteorP** [comment]
1. it's a setting, sorry that i forgot to write it in the lexica
2. in fact there is a short period before it began to attack, maybe i should extend the time
3. no problem
