### ISSUE TITLE
Quantum Mana Buffer loses all internal mana upon closing and reopening game/server

### ISSUE THREAD

**Issue by katubug** [ExtraMeteorP/Extra-Botany#60]
One of my players reported this bug on our multiplayer server, and I was able to replicate it in singleplayer.

When our server restarts, all the placed Quantum Mana Buffers lose their stored mana. In singleplayer, this happens when completely exiting the game to desktop. It does not happen just when exiting to menu.

This only seems to be happening with the Quantum Mana Buffer, not the regular Mana Buffer.

Thank you for your time!

Versions:
ExtraBotany-r1.1-54
Botania r1.10-361
forge-1.12.2-14.23.5.2838-universal

My full modlist with versions is at the bottom of this post: http://enthusiasticraft.cf/modpack-update-1-5-3/

**Comment by ExtraMeteorP** [comment]
i believe this should be fixed in r55
