### ISSUE TITLE
References in the names of items.

### ISSUE THREAD

**Issue by TheDirectorX** [ExtraMeteorP/Extra-Botany#64]
### Are spelling mistakes made in references to the names of items or is it done on purpose?
_I know that the names are sometimes distort specifically to make Indirect reference._
Examples:
https://github.com/ExtraMeteorP/Extra-Botany/blob/3d21cd0ba0d68a1611c8ba630d4a003b3cf6c116/lang/en_us.lang#L42 
![image](https://user-images.githubusercontent.com/43481085/60400045-d6507c80-9b87-11e9-8781-1975019f0169.png)
https://github.com/ExtraMeteorP/Extra-Botany/blob/3d21cd0ba0d68a1611c8ba630d4a003b3cf6c116/lang/en_us.lang#L98
![image](https://user-images.githubusercontent.com/43481085/60400054-16176400-9b88-11e9-8414-e82f777a81f5.png)
_When I just translate into Russian, I try to keep the distortion of the references._

**Comment by ExtraMeteorP** [comment]
https://github.com/Vazkii/Botania/blob/1.7.10-final/src/main/java/vazkii/botania/common/item/relic/ItemExcaliber.java
vazkii named it Excaliber so I leave it as it is.
https://yugioh.fandom.com/wiki/Artifact_Achilleshield?file=ArtifactAchilleshield-MP15-EN-C-1E.png
It seems that I made a typo

**Comment by TheDirectorX** [comment]
**So how is it right? Just some people think that this is a typo and correct the translation.** https://github.com/ExtraMeteorP/Extra-Botany/pull/62#issue-293021149

**Comment by ExtraMeteorP** [comment]
if correcting the typo will no longer confuse people, correct it. In former French translation of botania it is Excalibur so I think both are ok
