### ISSUE TITLE
Bugs in ExtraBotany-r1.1-55

### ISSUE THREAD

**Issue by TheDirectorX** [ExtraMeteorP/Extra-Botany#69]
### [1] Gaia Guardian III
- [x] _(a)_ Gaia Guardian III spawns invisible.
- [x] _(b)_ Gaia Guardian III destroys liquid blocks only during teleportation.
![2019-08-01_00 30 20](https://user-images.githubusercontent.com/43481085/62246694-a520d180-b3fd-11e9-9e2b-29648448e409.png)
- [x] _(c)_ If you hit Guardian Gaia III, the screen will turn red tint. (Gaia causes some instant attack after hitting). I did not find a way to get rid of this, except to restart the game.
![2019-08-01_01 25 39](https://user-images.githubusercontent.com/43481085/62248194-f7afbd00-b400-11e9-8364-96800f575e27.png)
![2019-08-01_00 37 44](https://user-images.githubusercontent.com/43481085/62248195-f8485380-b400-11e9-82b4-d30780159f44.png)
### [2] Herrscher of the Void
- [x] _(a)_ Herrscher of the Void does not break any liquid blocks at all, because of this, the entities of Lance of Subspace float away. Also, Spear of Subspace collides with water and slows down.
![2019-08-01_01 08 43](https://user-images.githubusercontent.com/43481085/62249208-51b18200-b403-11e9-9063-718e3a495237.png)
### [3] Mana Cocktail
- [x] _(a)_ Mana Cocktail has the sound of eating when you drink.
![2019-07-26_04 42 26](https://user-images.githubusercontent.com/43481085/62249752-94278e80-b404-11e9-9412-717e7702cdc1.png)
### [4] Necrofleur in Lexica Botania
- [x] _(a)_ On the Necrofleur page in Lexica Botania: "Format error".
![2019-07-22_01 53 49](https://user-images.githubusercontent.com/43481085/62250017-42333880-b405-11e9-9ec7-0edee7823748.png)
### [5] Flux Manafield
- [x] _(a)_ No energy pipes connect to Flux Manafield. I know that this has already been discussed https://github.com/ExtraMeteorP/Extra-Botany/issues/15, but the same analogue of Flux Manafield – Mana Fluxfield from Botania easily connects any energy pipes.
![2019-08-01_00 48 19](https://user-images.githubusercontent.com/43481085/62250650-e79adc00-b406-11e9-88ef-88ef4e2fe112.png)
![2019-08-01_00 49 01](https://user-images.githubusercontent.com/43481085/62250651-e79adc00-b406-11e9-8cfa-1fdf24ff20f4.png)

**Comment by ExtraMeteorP** [comment]
thanks for reporting, i have archieved r55 and soon i will upload a fixed one

**Comment by TheDirectorX** [comment]
**Is it normal if the flying Spear of Subspace is slowed down by the blow of flowing water?**
![image](https://user-images.githubusercontent.com/43481085/62306404-40b44f80-b49b-11e9-9e0b-a17dc398ce50.png)

**Comment by TheDirectorX** [comment]
### ( ͡° ͜ʖ ͡°)
![2019-08-04_15 56 10](https://user-images.githubusercontent.com/43481085/62427164-4e224180-b708-11e9-8b2b-4fea2ada8298.png)
![2019-08-04_15 56 27](https://user-images.githubusercontent.com/43481085/62427165-4e224180-b708-11e9-81f7-3ecc23f5f12d.png)
