### ISSUE TITLE
Not able to put water in living rock pedestal

### ISSUE THREAD

**Issue by ryannadell** [ExtraMeteorP/Extra-Botany#76]
Maybe I am stupid I am attempting to use the meme of a flower "Annoying flower" simply out of curiosity while im in my base doing other things but cant seem to put water in the pedestal, I have tried buckets and the water rod and cant think of any other way to get water in there.

**Comment by ExtraMeteorP** [comment]
actually putting a bucket of water in it is just ok

**Comment by ExtraMeteorP** [comment]
and the pedestal should be at the same level of the flower

**Comment by ryannadell** [comment]
So like so? 
![image](https://user-images.githubusercontent.com/37358884/66354227-22068500-e932-11e9-92d4-6c66fb9481af.png)

**Comment by ExtraMeteorP** [comment]
sorry i dont notice there is a picture :( you should raise your pedestal 1 block higher
