### ISSUE TITLE
SpongeForge support

### ISSUE THREAD

**Issue by bigenergy** [ExtraMeteorP/Extra-Botany#77]
You support the platform SpongeForge?
Some things from your mod do damage in GriefPrevention (plugin for sponge) claims.
Spear of subspace, Excalibur - Any player on the server can kill animals or another player in his GP claim.
Other mods do not have such a problem, maybe you should use fakeplayer?

Thanks.

**Comment by ExtraMeteorP** [comment]
Got it. will try

**Comment by LemADEC** [comment]
Your projectile entities should derivate from the base game Entity Arrow or explicitly specify the source entity of the damage.
