### ISSUE TITLE
Mini Handbag bug

### ISSUE THREAD

**Issue by bigenergy** [ExtraMeteorP/Extra-Botany#78]
When changing hands, the entire contents of the bag is cleared

**Comment by ExtraMeteorP** [comment]
i cant understand what does “changing hands” mean

**Comment by bigenergy** [comment]
Shift the bag into the second hand of the character

**Comment by Lewui** [comment]
> i cant understand what does “changing hands” mean


I think he wanted to say that when you switch hands, items disappear.

**Comment by bigenergy** [comment]
It seems like this only happens in creative mode.
