### ISSUE TITLE
Quantum Mana Buffer cannot output to Quantum Mana Buffer

### ISSUE THREAD

**Issue by Xavion3** [ExtraMeteorP/Extra-Botany#79]
It seems like while either buffer can output to a buffer above them, they cannot output to a quantum mana buffer above them. My guess is it looks like this is because they aren't actually subclassed out of mana buffers, and only check for normal mana buffers in [the code](https://github.com/ExtraMeteorP/Extra-Botany/blob/master/src/main/java/com/meteor/extrabotany/common/block/tile/TileQuantumManaBuffer.java#L88-L102), not quantum mana buffers.

**Comment by ExtraMeteorP** [comment]
Yes, will improve. I just think maybe no one will use more than one quantum :P

**Comment by Xavion3** [comment]
I've got 5 quantums, how I ran into it. It is absolutely overkill, but I did it because I can craft them relatively easily at the point I'm at and I wanted to hide my mana generation underground so use a small tower of quantum buffers to transfer it up to the surface.

It is definitely a niche scenario though.

**Comment by ExtraMeteorP** [comment]
done in r57
