### ISSUE TITLE
[Unbalanced] Judah Koath

### ISSUE THREAD

**Issue by NikeSchuh** [ExtraMeteorP/Extra-Botany#83]
Minecraft Version : 1.12.2
Multiplayer : Yes
Extra Botany Version : ExtraBotany-r1.1-56.jar

I have the full set of Draconic Armor  (Draconic Evolution)  and the Damage of the Judah Koath just goes throw my Shield and one shots me. Actually i cant be killed i get revived if i die but the Juda Koath seems to ignore everything and just /kill me.
Its even sending the message of /kill.
Its also damaging me while I have the Avaritia Armor on! This Armor is equal to creative mode ...

**Comment by ExtraMeteorP** [comment]
nerf in r57
