### ISSUE TITLE
打空之律者人参（不死图腾）没有用

### ISSUE THREAD

**Issue by 37385** [ExtraMeteorP/Extra-Botany#84]
版本 ExtraBotany-r1.1-54
复现过程：双手拿着不死图腾，等待。然后直接死亡。没有出现不死图腾的动画。

**Comment by ExtraMeteorP** [comment]
大概是不死图腾不会响应虚空伤害

**Comment by 37385** [comment]
@ExtraMeteorP  哦，没有解决方法吗？

**Comment by 37385** [comment]
@ExtraMeteorP  那我几箱子人参没有用了呀。

**Comment by ExtraMeteorP** [comment]
介个是设定呢
