### ISSUE TITLE
Manalinkium null pointer exception

### ISSUE THREAD

**Issue by amejsia** [ExtraMeteorP/Extra-Botany#91]
#### 摆放魔链花之后服务器后台报错，在本地可以复现  
```
 java.lang.NullPointerException: Ticking block entity
at com.meteor.extrabotany.common.block.subtile.functional.SubTileManalinkium.onUpdate(SubTileManalinkium.java:84)
...
```
就来github查了下源码，就觉得很奇怪
https://github.com/ExtraMeteorP/Extra-Botany/blob/5ee1ea895ae30761f7af07913bcee94e779c0538/src/main/java/com/meteor/extrabotany/common/block/subtile/functional/SubTileManalinkium.java#L81-L89
反编译了一下之后发现不一样
```java
    IManaPool pool = getManaPool(new BlockPos(this.x, this.y, this.z), this.dim);
    if (!(pool instanceof DummyPool) && 
      !(this.supertile.func_145831_w()).field_72995_K && 
      this.mana >= ConfigHandler.SPEED && !pool.isFull()) {
      this.mana -= ConfigHandler.SPEED;
      pool.recieveMana(ConfigHandler.SPEED);
    } 
```
查了一下mcp，`if`的判断是
`!(this.supertile.getWorld()).isRemote`
才发现github上是r56本地玩的是r57  
再找的时候注意到了
>2. mana duplication caused by manalinkium because i didn't use !world.isRemote

_Originally posted by @ExtraMeteorP in https://github.com/ExtraMeteorP/Extra-Botany/issues/80#issuecomment-557126173_

#### 于是猜测是不是r57少了一个空指针的判断之后，仍会出现`pool`为空的状况，导致84行的`!pool.isFull()`报出`NullPointerException`
  
 现在因为有人种在出生点区块服务器打不开了_(:з)∠)_希望尽快修复~~顺便把r57更新过来吧~~  
  
Still a great mod though! Love it :D

**Comment by amejsia** [comment]
服务器打不开的问题暂时通过修改`extrabotany.cfg`中的
```
"enable flowers" {
    ...
    B:manalinkium=true
    ...
}
```
改为`false`解决了  

config太齐全真是帮大忙了  
  
nb！

**Comment by ExtraMeteorP** [comment]
update
