### ISSUE TITLE
EntitySubspaceSpear doesn't check if thrower is a Player

### ISSUE THREAD

**Issue by gabizou** [ExtraMeteorP/Extra-Botany#92]
From SpongePowered/SpongeForge#3083:

A user spawned a Herrscher which ends up spawning an `EntitySubspaceSpear` by proxy of the `EntitySubspace`, and there's a class cast exception that gets spammed:
https://gist.github.com/SSKirillSS/9d5bdae5fa868e6311209d9b642ec759

This looks like a mod bug:
The [`Herrscher` is spawning an `EntitySubSpace` with itself as the `thrower`](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/gaia/EntityVoidHerrscher.java#L234) (whose [constructor accepts `EntityLivingBase`](https://github.com/ExtraMeteorP/Extra-Botany/blob/293cfc81f0b22bd72a8b99baa087f77581b426bc/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspace.java#L52),  which during the [`EntitySubSpace` tick of a type `1`, it'll spawn an `EntitySubSpaceSpear`](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspace.java#L94) (which again, accepts a [`similar constructor`](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspaceSpear.java#L47)) and during the [`EntitySubspaceSpear`'s update, it incorrectly casts the thrower as `EntityPlayer` without checking](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspaceSpear.java#L80-L89). 

This in itself is a mod bug that Sponge has prevented potentially crashing outright on the cast and causing a full server tick crash.

I'd go ahead and submit the bug report to the Extra-Botany repository for the dev to make the simple fix (which it looks like they do have some copy pasted code from [here, that correctly checks the thrower is an instance of `EntityPlayer`](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspace.java#L78-L85) but I'm not an expert of what their logic is attempting to do.

**Comment by ExtraMeteorP** [comment]
thank you for letting me know

**Comment by SSKirillSS** [comment]
Any info about this?

**Comment by SSKirillSS** [comment]
(sounds of waiting)
