### ISSUE TITLE
Server performance degradation due to advances

### ISSUE THREAD

**Issue by bigenergy** [ExtraMeteorP/Extra-Botany#95]
ExtraBotany checks the player’s achievements and his inventory and this carries a high load on the server
https://spark.lucko.me/#6ViRikfjDq

![image](https://user-images.githubusercontent.com/17977139/78263380-8df52f00-750a-11ea-8d92-46ebda6019e4.png)

**Comment by bigenergy** [comment]
@ExtraMeteorP Add the option to disable this

**Comment by LemADEC** [comment]
Any update on this?
